# Protection rofi
bindr = SUPER ,SUPER_L ,exec ,pkill rofi || rofi -show drun -display-drun "> " -i -p "test" -l 5 -theme "~/.config/rofi/appLauncher/appLauncher.rasi"

# PowerMenu
bindr = SUPER ,P ,exec ,pkill wlogout || wlogout -p layer-shell

# Workspace movement
bind = SUPER + ALT_L, LEFT, workspace, -1
bind = SUPER + ALT_L, RIGHT, workspace, +1
bind = SUPER + ALT_L, UP, movetoworkspace, +1
bind = SUPER + ALT_L, DOWN, movetoworkspace, -1
bind = SUPER, S, togglespecialworkspace, magic

# Fullscreen
bind = SUPER, V, fullscreen, 1

# Lock
bind = SUPER, L, exec, swaylock

# Exec
bind = SUPER, F, exec, zen-browser
bind = SUPER_SHIFT_L, S, exec, grimblast copy area
bind = SUPER, T, exec, wezterm
bind = SUPER, D, exec, sh ~/.config/hypr/scripts/legcordControl.sh

# Shortcuts
bind = SUPER, C, killactive

# Focus
bind = SUPER, LEFT, movefocus, l
bind = SUPER, RIGHT, movefocus, r
bind = SUPER, UP, movefocus, u
bind = SUPER, DOWN, movefocus, d

# Window movement
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, W, togglefloating
